;;; init.el --- Configuration of Emacs
;;
;; (c) 2000 - 2020 Robert Štojs
;;

;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(package-initialize)

(require 'org)
(require 'ob-tangle)

(setq init-dir (file-name-directory (or load-file-name (buffer-file-name))))
(org-babel-load-file (expand-file-name "loader.org" init-dir))

;;; This stuff is autogenerated
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(highlight ((t (:background "#444"))))
 '(line-number ((t (:inherit font-lock-comment-delimiter-face))))
 '(line-number-current-line ((t (:inherit font-lock-constant-face))))
